"""
Django settings for newsapi project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import cloudinary
import cloudinary.uploader
import cloudinary.api
from decouple import config 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'django_filters',
    'cloudinary',
    'drf_spectacular',
    
    # Local apps
    'articles',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newsapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsapi.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'  # Custom user model


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': config('DATABASE_NAME'),
		'USER': config('DATABASE_USER'),
		'PASSWORD': config('DATABASE_PASSWORD'),
		'HOST': config('DATABASE_HOST'),
		'PORT': config('DATABASE_PORT'),
	}
}

cloudinary.config(
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET'),
    cloud_name=config('CLOUDINARY_CLOUD_NAME')
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',    
    ],
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    
    
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Compass NewsAPI',
    'DESCRIPTION': """
## Overview
A full-featured news platform API built with Django REST Framework.

## Authentication
All protected endpoints require a **JWT Bearer token**. Obtain tokens via the `/auth/login/` endpoint and include them in the `Authorization` header:
```
Authorization: Bearer <access_token>
```

## Features
- **Authentication** — JWT-based login & registration
- **Role-based access control** — superadmin, admin, editor, journalist, reader
- **Articles** — Full CRUD with publish/unpublish workflow
- **Categories** — Article categorization
- **Filtering & Search** — Filter by status, category, featured; search by title/content
- **Ordering** — Sort by published date, created date, or view count
- **Cloudinary** — Media management for profile pictures and article images
    """,
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Compass NewsAPI Support',
        'email': 'support@compass-news.api',
    },
    'LICENSE': {
        'name': 'MIT',
    },

    'SERVE_INCLUDE_SCHEMA': False,

    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': False,
        'syntaxHighlight.activate': True,
        'syntaxHighlight.theme': 'monokai',
    },

    'COMPONENT_SPLIT_REQUEST': True,

    'TAGS': [
        {'name': 'Authentication', 'description': 'User registration, login, and token management.'},
        {'name': 'Users', 'description': 'User management, profile updates, role assignments, and account activation.'},
        {'name': 'Articles', 'description': 'Create, read, update, delete, publish, and unpublish news articles.'},
        {'name': 'Categories', 'description': 'Manage article categories.'},
    ],

    'SECURITY': [{'jwtAuth': []}],
}

# Simple JWT configuration: set token lifetimes
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=24),
}